train:
  _target_: dobbe.dataloaders.decord_dataset.DecordDataset
  config:
    _target_: dobbe.dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.finetune_task_data_root}
    trajectory_roots:
      _target_: dobbe.dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.train.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.finetune_task_data_original_root}
      new_root: ${dataset.train.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    include_envs: 
      - ${include_env}
    sequence_length: 1
    trajectory_subsample_fraction: 1.0
    control_timeskip: 7
    fps_subsample: 1
    relative_gripper: False
    use_depth: ${use_depth}
    binarize_gripper: false
    binarize_gripper_threshold: 0.8
    binarize_gripper_upper_value: 1.0
    binarize_gripper_lower_value: 0.35
  max_videoreaders_in_memory: 128
  shuffle_mode: RANDOM_ORDER
  device: cpu


test:
  _target_: dobbe.dataloaders.decord_dataset.DecordDataset
  config:
    _target_: dobbe.dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.finetune_task_data_root}
    trajectory_roots:
      _target_: dobbe.dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.test.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.finetune_task_data_original_root}
      new_root: ${dataset.test.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    include_envs: 
      - ${include_env}_val
    sequence_length: ${dataset.train.config.sequence_length}
    control_timeskip: ${dataset.train.config.control_timeskip}
    fps_subsample: ${dataset.train.config.fps_subsample}
    relative_gripper: ${dataset.train.config.relative_gripper}
    use_depth: ${use_depth}
    binarize_gripper: ${dataset.train.config.binarize_gripper}
    binarize_gripper_threshold: ${dataset.train.config.binarize_gripper_threshold}
    binarize_gripper_upper_value: ${dataset.train.config.binarize_gripper_upper_value}
    binarize_gripper_lower_value: ${dataset.train.config.binarize_gripper_lower_value}
  max_videoreaders_in_memory: 128
  shuffle_mode: SEQUENTIAL
  device: cpu
