train:
  _target_: dataloaders.decord_dataset.DecordDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.home_ssl_data_root}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${env_vars.home_ssl_data_root}/r3d_files.txt
      original_root: ${env_vars.home_ssl_data_original_root}
      new_root: ${env_vars.home_ssl_data_root}
    exclude_tasks:
    exclude_homes:
      - "Home6"
    exclude_envs: []
    sequence_length: 1
    control_timeskip: 1
    fps_subsample: 8
  max_videoreaders_in_memory: 512
  shuffle_mode: RANDOM_ORDER
  device: cpu

test:
  _target_: dataloaders.decord_dataset.DecordDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.home_ssl_data_root}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${env_vars.home_ssl_data_root}/r3d_files.txt
      original_root: ${env_vars.home_ssl_data_original_root}
      new_root: ${env_vars.home_ssl_data_root}
    exclude_tasks:
    include_homes:
      - "Home6"
    exclude_envs: []
    sequence_length: 1
    control_timeskip: 1
    fps_subsample: 8
  max_videoreaders_in_memory: 128
  shuffle_mode: SEQUENTIAL
  device: cpu
