_target_: models.policies.bc.BCDepthModel
encoder:
  _target_: models.encoders.baseline_enc.vc1.VC1
  override_aug_kwargs:
    hflip: 0.0
    vflip: 0.0
    gaussblr: 0.15
    grayscale: 0.15
    scale: [1.0, 1.0]
    crop_pct: 0.875

enc_weight_pth: null
model_weight_pth: null
use_depth: ${use_depth}
depth_patch_dim: 4
depth_kernel_size: [12, 16]

relative_gripper: ${dataset.train.config.relative_gripper}
