defaults:
  - env_vars: env_vars
  - dataset:  finetune_task_data
  - model: image_bc_depth_timm
  - loss_fn: bc_loss
  - _self_

num_epochs: 50
eval_every: 1
device: cuda
batch_size: 256
use_depth: true

include_task: Drawer_Opening
include_env: Env1

sampler: null

batch_sampler:
  _target_: dobbe.dataloaders.decord_dataset.DecordBatchSampler
  batch_size: ${batch_size}

dataloader:
  _target_: dobbe.dataloaders.decord_dataloader.DecordVideoLoader
  device: cpu
  num_workers: 8


optimizer:
  _target_: torch.optim.Adam
  lr: 0.00003
  weight_decay: 1.5e-6

scheduler:
  _target_: dobbe.models.ssl.moco.optimizer.MoCoScheduler
  warmup_epochs: 10
  start_lr: 2e-6
  num_epochs: ${num_epochs}


model_path: checkpoints/${now:%Y-%m-%d}/${include_task}-${include_env}-moco-${now:%H-%M-%S}
resume_training: false
save_every: 10

wandb:
  entity: ${env_vars.wandb.entity}
  project: dobbe-${include_task}
  name: ${include_task}-${include_env}-moco-4x4
  # id starts out null, hoawever, if you resume training, it will be set to the original id.
  id: null
  save_code: true

seed: 42
