defaults:
  - env_vars: env_vars
  - model: image_bc_depth_timm
  - dataset: debug
  - _self_

image_save_dir: ${env_vars.project_root}/robot_images
image_buffer_size: 1
device: cpu

include_task: cactus
include_env: default_env

model_weight_pth: ${env_vars.project_root}/checkpoints/2024-05-07/cactus-default_env-moco-13-27-02/checkpoint_40.pt

experiment: bc_with_hpr_encoder
batch_size: 32
sampler: null
run_offline: true
use_depth: true

robot_params:
  h: 0.44
  max_h: 0.08
  max_base: 0.08
  abs_gripper: True
  rot_unit: axis

wandb:
  entity: ${env_vars.wandb.entity}
  project: imitation-in-homes
  id: null
  save_code: true
