defaults:
  - env_vars: env_vars
  - model: image_vinn
  - dataset: vinn_deploy_dataset
  - _self_

image_save_dir: ${env_vars.project_root}/robot_images
image_buffer_size: 1
device: cpu

# Path to encoder weights. You can download it from the link below.
# https://dl.dobb-e.com/models/hpr_model.pt
checkpoint_path: /home/hello-robot/encoders/hpr_model.pt

experiment: vinn_with_hpr_encoder
batch_size: 32
sampler: null
run_offline: false
use_depth: false

batch_sampler:
  _target_: dataloaders.decord_dataset.DecordBatchSampler
  batch_size: ${batch_size}
  num_replicas: 1

dataloader:
  _target_: dataloaders.decord_dataloader.DecordVideoLoader
  device: cpu
  num_workers: 8


robot_params:
  h: 0.44
  max_h: 0.08
  max_base: 0.08
  abs_gripper: True
  rot_unit: axis

wandb:
  entity: ${env_vars.wandb.entity}
  project: imitation-in-homes
  id: null
  save_code: true

