defaults:
  - env_vars: env_vars
  - dataset: debug
  - model: moco
  - loss_fn: moco_loss
  - _self_

num_epochs: 60
eval_every: 5
device: cuda
# batch_size: 800
batch_size: 256
use_depth: true

include_task: cactus
include_env: default_env

sampler: null

batch_sampler:
  _target_: dobbe.dataloaders.decord_dataset.DecordBatchSampler
  batch_size: ${batch_size}

dataloader:
  _target_: dobbe.dataloaders.decord_dataloader.DecordVideoLoader
  device: cpu
  num_workers: 10

optimizer:
  _target_: timm.optim.Lars
  lr: 0.6
  momentum: 0.9
  weight_decay: 1.0e-6

scheduler:
  _target_: dobbe.models.ssl.moco.optimizer.MoCoScheduler
  warmup_epochs: 70
  num_epochs: ${num_epochs}

# Model saving and loading
model_path: checkpoints/dobbe-moco-all
resume_training: false
save_every: 5

wandb:
  entity: ${env_vars.wandb.entity}
  project: dobbe-moco-all
  # id starts out null, hoawever, if you resume training, it will be set to the original id.
  id: null
  save_code: true

seed: 42
